### PR TITLE
Dockerfile

### PR DESCRIPTION
**Pull request by algas**
### What and why?

A short description of what changes this PR introduces and why.

We need your official-published Docker image.
See #296

### How?

A brief description of implementation details of this PR.

A Dockerfile to run `datadog-ci` command.

### Review checklist

- [ ] Feature or bugfix MUST have appropriate tests (unit, integration)

I would like you to build it and publish the docker image.

### CODE REVIEW

**Comment by algas** [comment]
I close it now because it has some problems which git commands do not work. I will fix it and send a PR.

**Comment by algas** [comment]
> I close it now because it has some problems which git commands do not work. I will fix it and send a PR.

I fixed these problems and tested it in my local environment.

**Comment by algas** [comment]
Usage
```
docker build -t datadog/datadog-ci:latest .
docker run --rm --env DATADOG_API_KEY=YOUR_KEY --env DD_ENV=YOUR_ENV --volume /path/to/git/working_root:/work:ro --volume /path/to/test/results:/test-results --workdir /work -t datadog/datadog-ci:latest junit upload --service YOUR_SERVICE_NAME /test-results
```

**Comment by m-rousse** [comment]
Hi, thanks for your interest in this feature.
We do not have plans to support an official Docker image as of now, but we will document an example Dockerfile in the README.

**Comment by m-rousse** [comment]
Here is the PR adding the instructions: https://github.com/DataDog/datadog-ci/pull/558

**Pull request closed without merging**
