### PR TITLE
[dep] Bump `@google-cloud/logging` to `v11`

### PR DESCRIPTION
**Pull request by duncanista**
### What and why?

#1122 

### How?

Upgraded dependency.

### Review checklist

- [ ] Feature or bugfix MUST have appropriate tests (unit, integration)

### CODE REVIEW

**Review by Drarig29 — APPROVED** [review]
LGTM. Nothing major changed [between the versions](https://github.com/googleapis/nodejs-logging/releases), apart from a migration [from Node 12.x to Node 14.x](https://github.com/googleapis/nodejs-logging/commit/c294f5d439eea69826d9ba6cb66f00adaf428878#diff-0186f53b45e19984a47319509fec85f490eeeb4a081867434ee4b8abfe438912R11), which we do support 👍

**Comment by hernancondoriipsy** [comment]
Can we merge this pr?

**Comment by Drarig29** [comment]
@hernancondoriipsy we'll release this change next week

**Comment by Drarig29** [comment]
@hernancondoriipsy released in [v2.24.1](https://github.com/DataDog/datadog-ci/releases/tag/v2.24.1)

**Pull request merged**
