### PR TITLE
Enforce Node.js 10

### PR DESCRIPTION
**Pull request by yoannmoinet**
### What and why?

We don't document which Node version we support.

### How?

- Add a badge in the README
- Update actions to use Node.js 10.24.1
- Update types for Node.js 10
- Add `engines` entry to the `package.json`
- Add a `.node-version` file to target `v10.24.1`

### Review checklist

- [ ] Feature or bugfix MUST have appropriate tests (unit, integration)

### CODE REVIEW

**Review by sdeprez — APPROVED** [review]
Thanks!

**Review by m-rousse — APPROVED** [review]
Thanks :bow:
(It looks like the `crypto.ts` file fails the typings)

**Comment by yoannmoinet** [comment]
`crypto.ts` will be fixed in this PR later.

https://datadoghq.atlassian.net/browse/SW-1074

**Review by m-rousse — APPROVED** [review]
All good from infra + synthetics PoV (I could successfully run a tunneled test with these changes).

**Comment by yoannmoinet** [comment]
Super cool, thanks a ton @etnbrd !

**Pull request merged**
