### PR TITLE
v0.17.9

### PR DESCRIPTION
**Pull request by cg14823**
### What and why?

Release a new version of the datadog-ci which generates the correct pipeline URLs for GitHub actions in the `trace` and `junit` command.

### Review checklist

- [ ] Feature or bugfix MUST have appropriate tests (unit, integration)
- [ ] A new release of `datadog-ci` MUST be updated in the [synthetics-ci-github-action](https://github.com/DataDog/synthetics-ci-github-action)

### CODE REVIEW

**Comment by cg14823** [comment]
>  A new release of datadog-ci MUST be updated in the synthetics-ci-github-action

Not sure exactly what I have to do here.

**Review by edrevo — APPROVED** [review]

**Review by tonyredondo — APPROVED** [review]

**Comment by juan-fernandez** [comment]
> > A new release of datadog-ci MUST be updated in the synthetics-ci-github-action
> 
> Not sure exactly what I have to do here.

do you maybe know @m-rousse? It appears in the PR description

**Comment by m-rousse** [comment]
My bad, it has been merged to the instructions without the repo actually being used and advertised internally.
I'll publish a RFC around that soon (this week). In the meantime, feel free to merge/publish as usual, I'll remove this line

**Review by juan-fernandez — APPROVED** [review]

**Comment by juan-fernandez** [comment]
> My bad, it has been merged to the instructions without the repo actually being used and advertised internally. I'll publish a RFC around that soon (this week). In the meantime, feel free to merge/publish as usual, I'll remove this line

thanks for the info!

**Comment by m-rousse** [comment]
(Pull request template has been updated!)

**Review by m-rousse — APPROVED** [review]

**Pull request merged**
