### PR TITLE
Export datadog-ci as a library - 1/2

### PR DESCRIPTION
**Pull request by etnbrd**
### What and why?

This PR replace the root and all command `index.ts` with `cli.ts` to later leave the `index.ts` be able to export `datadog-ci` as a library.

---

part 1/2 https://github.com/DataDog/datadog-ci/pull/432
part 2/2 https://github.com/DataDog/datadog-ci/pull/433

### CODE REVIEW

**Review by yoannmoinet — APPROVED** [review]
LGTM, well done.

**Review by juan-fernandez — APPROVED** [review]
LGTM

**Review by m-rousse — APPROVED** [review]

**Review by lraucy — APPROVED** [review]

**Comment by etnbrd** [comment]
Somehow I can't merge this, despite the 4 approvals 🤔 
I thought maybe it's because of the rum-mobile pending review, but I can't remove them from the reviewers.
@DataDog/rum-mobile could you either submit a review, or remove yourself from the reviewers, to see if we can merge this then?

Screenshot 2021-12-06 at 1 47 50 PM

**Review by maxep — APPROVED** [review]
👍

**Pull request merged**
