### PR TITLE
Add new ap1.datadoghq.com site

### PR DESCRIPTION
**Pull request by troisdiz**
### What and why?

Add a reference to the newly GA Datadog site: ap1.datadoghq.com.

### How?

Add an entry in the list of sites

### Review checklist

- [ ] Feature or bugfix MUST have appropriate tests (unit, integration)

### CODE REVIEW

**Review by loutPhilipps — COMMENTED** [review]
Can we also add a test in https://github.com/DataDog/datadog-ci/blob/master/src/helpers/__tests__/validation.test.ts?

Ideally also for Synthetics in https://github.com/DataDog/datadog-ci/blob/c4a338826ffc3a11c96d014c12f2c88e5f5e34ac/src/commands/synthetics/__tests__/utils.test.ts#L1090

**Review by loutPhilipps — COMMENTED** [review]
I see that you added the test for Synthetics, what about having one too in https://github.com/DataDog/datadog-ci/blob/c4a338826ffc3a11c96d014c12f2c88e5f5e34ac/src/helpers/__tests__/validation.test.ts#L13-L15?

**Review by loutPhilipps — APPROVED** [review]

**Comment by troisdiz** [comment]
> I see that you added the test for Synthetics, what about having one too in
> 
> https://github.com/DataDog/datadog-ci/blob/c4a338826ffc3a11c96d014c12f2c88e5f5e34ac/src/helpers/__tests__/validation.test.ts#L13-L15
> 
> ?

Not sure it adds (like the previous commit) much value but added it for consistency

**Review by lefebvree — APPROVED** [review]
LGTM

**Review by Drarig29 — APPROVED** [review]

**Pull request merged**
